#!/bin/bash
# PreToolUse/Write|Edit: refuse edits to files XcodeGen generates from project.yml.
f=$(jq -r '.tool_input.file_path // empty')
case "$f" in
  *.pbxproj|*.xcodeproj/*|*/App/Info.plist|*/Widget/Info.plist|*.entitlements)
    echo "Blocked: $f is generated by XcodeGen and discarded on the next 'xcodegen generate'. Edit project.yml instead, then run xcodegen generate." >&2
    exit 2 ;;
esac
exit 0
